name: "ArchLinux (makepkg)"
description: "ArchLinux (makepkg)"
author: shyaminayesh
branding:
  color: blue
  icon: box
inputs:
  cmd:
    description: "makepkg build arguments"
    required: true
    default: '--printsrc'
  pkgbuilds:
    description: "PKGBUILD files"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
