name: "ArchLinux (makepkg)"
description: "ArchLinux (makepkg)"
inputs:
  cmd:
    description: "makepkg build arguments"
    required: true
    default: '--printsrc'
  package:
    description: "package directory"
    required: true
    default: '.'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cmd }}
