name: "ArchLinux (makepkg)"
description: "ArchLinux (makepkg)"
author: shyaminayesh
inputs:
  cmd:
    description: "makepkg build arguments"
    required: true
    default: '--printsrc'
  package:
    description: "package name"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
